// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw6TW_D8T7JUQ5UyCo8l4PxLVzStVG-Qs',
    appId: '1:471760942637:web:172ad29db424387d85eaa4',
    messagingSenderId: '471760942637',
    projectId: 'mobdev-finals',
    authDomain: 'mobdev-finals.firebaseapp.com',
    storageBucket: 'mobdev-finals.appspot.com',
    measurementId: 'G-B1QLEMFBC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg2zxBCeNUOdJB5JM-bSBUtABSl7SYFkk',
    appId: '1:471760942637:android:13609578e630479385eaa4',
    messagingSenderId: '471760942637',
    projectId: 'mobdev-finals',
    storageBucket: 'mobdev-finals.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb-9atkKYr90ZxfBJhf8m1Rl0E9KT0U4o',
    appId: '1:471760942637:ios:9c133d27e80920bc85eaa4',
    messagingSenderId: '471760942637',
    projectId: 'mobdev-finals',
    storageBucket: 'mobdev-finals.appspot.com',
    iosBundleId: 'com.example.mobdevFinalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb-9atkKYr90ZxfBJhf8m1Rl0E9KT0U4o',
    appId: '1:471760942637:ios:ba0908986f36cc6885eaa4',
    messagingSenderId: '471760942637',
    projectId: 'mobdev-finals',
    storageBucket: 'mobdev-finals.appspot.com',
    iosBundleId: 'com.example.mobdevFinalApp.RunnerTests',
  );
}
